name: "Fosstars (OSS rules of play)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: "Open source rules of play"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
          # Optional (defaults to the current repository).
          repository: fosstar-test-org/refactored-octo-invention
      - uses: ./.github/actions/oss-rules-of-play-action
        with:
          fosstars-version: oss-rules-of-play
          report-branch: fosstars-oss-rules-of-play-test-report
          token: "${{ steps.generate_token.outputs.token }}"
