name: "Fosstars (OSS rules of play)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: "Open source rules of play"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Generate token
        id: generate_token
        uses: jnwng/github-app-installation-token-action@v2
        with:
          appId: ${{ secrets.APP_ID }}
          installationId: 16058531
          privateKey: ${{ secrets.APP_PEM }}
      - name: api-call
        id: test
        run: "curl -v -u token:${{ steps.generate_token.outputs.token }} -H 'Accept: application/vnd.github.dorian-preview+json' https://api.github.com/repos/fosstar-test-org/refactored-octo-invention/vulnerability-alerts"
      - uses: ./.github/actions/oss-rules-of-play-action
        with:
          fosstars-version: oss-rules-of-play
          report-branch: fosstars-oss-rules-of-play-test-report
          token: "${{ steps.generate_token.outputs.token }}"
